import configparser


# CONFIG
config = configparser.ConfigParser()
config.read('dwh.cfg')

# DROP TABLES

staging_events_table_drop = "DROP TABLE IF EXISTS staging_events"
staging_songs_table_drop = "DROP TABLE IF EXISTS staging_songs"
songplay_table_drop = "DROP TABLE IF EXISTS songplay_table"
user_table_drop = "DROP TABLE IF EXISTS user_table"
song_table_drop = "DROP TABLE IF EXISTS song_table"
artist_table_drop = "DROP TABLE IF EXISTS artist_table"
time_table_drop = "DROP TABLE IF EXISTS time_table"

# CREATE TABLES

staging_events_table_create= ("""
""")

staging_songs_table_create = ("""
""")

songplay_table_create = ("""
CREATE TABLE songplays ( 
    songplay_id INT GENERATED BY DEFAULT AS IDENTITY(0,1),
    start_time TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    level VARCHAR(10) NOT NULL,
    song_id CHAR(18),
    artist_id CHAR(18),
    session_id INT NOT NULL,
    location VARCHAR(50) NOT NULL,
    user_agent VARCHAR(150) NOT NULL
) ;
""")

user_table_create = ("""
CREATE TABLE users (
    user_id INT PRIMARY KEY,
    first_name VARCHAR(10) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    gender CHAR(1) NOT NULL,
    level VARCHAR(10) NOT NULL
)
""")

song_table_create = ("""
CREATE TABLE songs (
    song_id CHAR(18) PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    artist_id CHAR(18) NOT NULL,
    year INT NOT NULL,
    duration NUMERIC(18,6) NOT NULL
)
""")

artist_table_create = ("""
CREATE TABLE artists (
    artist_id CHAR(18) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(50) NOT NULL,
    latitude NUMERIC(18,6) NULL,
    longitude NUMERIC(18,6) NULL
)
""")

time_table_create = ("""
CREATE TABLE time (
    start_time timestamp PRIMARY KEY,
    hour INT NOT NULL,
    day INT NOT NULL,
    week INT NOT NULL,
    month INT NOT NULL,
    year INT NOT NULL,
    weekday INT NOT NULL
)
""")

# STAGING TABLES

staging_events_copy = ("""
""").format()

staging_songs_copy = ("""
""").format()

# FINAL TABLES

songplay_table_insert = ("""
""")

user_table_insert = ("""
""")

song_table_insert = ("""
""")

artist_table_insert = ("""
""")

time_table_insert = ("""
""")

# QUERY LISTS

create_table_queries = [staging_events_table_create, staging_songs_table_create, songplay_table_create, user_table_create, song_table_create, artist_table_create, time_table_create]
drop_table_queries = [staging_events_table_drop, staging_songs_table_drop, songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]
copy_table_queries = [staging_events_copy, staging_songs_copy]
insert_table_queries = [songplay_table_insert, user_table_insert, song_table_insert, artist_table_insert, time_table_insert]
